version: '3'

services:
  mongo:
    image: mongo:4.2
    restart: always
    volumes:
      - mongo_data:/data/db

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    environment:
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    restart: always
    volumes:
      - es_data:/usr/share/elasticsearch/data

  graylog:
    image: graylog/graylog:4.2
    environment:
      GRAYLOG_PASSWORD_SECRET: some_random_secret_please_change
      GRAYLOG_ROOT_PASSWORD_SHA2: 5994471abb01112afcc18159f6cc74b4f511b99806da59b3caf5a9c173cacfc5
      GRAYLOG_HTTP_EXTERNAL_URI: http://localhost:9000/
    depends_on:
      - mongo
      - elasticsearch
    ports:
      - "9000:9000"
      - "12201:12201/udp"
      - "5044:5044"
    restart: always
    volumes:
      - graylog_data:/usr/share/graylog/data

volumes:
  mongo_data:
  es_data:
  graylog_data:
